name: Release

on:
  workflow_dispatch:
    inputs:
      version: 
        required: true
        type: string
        description: Release version number (semver)
      prerelease: 
        required: false
        default: false
        type: boolean
        description: Is it pre-release version?

# on:
#   workflow_dispatch:
#     inputs:
#       version: 
#         required: true
#         type: string
#         description: Release version number (semver)
#       prerelease: 
#         required: false
#         default: false
#         type: boolean
#         description: Is it pre-release version?

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      
      - name: Install and Build 🔧
        run: |
          npm install
          npm run production
          rm dist/.gitignore
          npm run zip
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: ${{ github.event.inputs.prerelease }}
          tag_name: ${{ github.event.inputs.version }}
          files: |
            dist.zip
